apiVersion: v1
kind: Service
metadata:
  name: apiworkflow2
  namespace: sample-app-namespace-1750930897184
  labels:
    app.kubernetes.io/name: apiworkflow2
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: apiworkflow2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080