apiVersion: v1
kind: Service
metadata:
  name: apiworkflow
  namespace: sample-app-namespace-1751004940473
  labels:
    app.kubernetes.io/name: apiworkflow
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: apiworkflow
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080